language: node_js
node_js:
- '4.3'
script:
- npm install
- npm test
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: e5PPXeimIDaMuelnWps0tjdbUcTye6wtSR+hrLFvmfej5vPazeokeq711Otoa09Ld5fNZRt2qCUioHQIoSjm2kQYOzjXoSOfdKBs/nXPOp1WT7pJEhiqBjq5X46Sa1pO/HvevCkt522FBqjYR+vPTRSpP/nAgAiV5hPXF/JlfU4Lvn9KlaxBMOlpxpW7N0SDwpj4uShUnQZlyyvwjJQwKmZRXIp3mhM2xh8nKH239sVlemrY+CbzWx02G1T9qhLIr28YpWDVm6+ZIbiB6GGNINduANqQsklb3kXSasuXU8LRvMMXJsInck5t5cu79hveTMQLfHAjzcbVWclGTJqV7ryu6nBpTLFAdMCxcDj0q45++5X6oX3mIMAirQU1Zyl861y418K5A6pw8K1xzhmFwNXgOTlR8HOrGz5AMIO4rXoWWiDl36t45p0x0b0J/SLHYXf9i6Gu8NhWE4rYPnXTLPKs7RS+Ew8QvxUnDye+H/EP4yRh6FVJIssirbo94eBIMhzzoHzqB43siu8WzmCd3vDYd/Oi+Qu5JZmbhcv5kfVxrKm1a6fDB9j54GzTryu6Msa42hYtRVm92OVOTAUEv49wRQiJwQ8fqy+4XwCRzyF5i0Gfa+3W7012UsiKoJMPpZ/smjfz9qUPhYuhXwIA6CdgEkW+7M+ju+xh80H3uro=
  - secure: mFsxpFVuFCybeDcUkCxbP2VZeALy4X6/RjFmpF1yfblCQEb3uttOkX7KuWstoggAHuvlYm1W16riP7I7yYFEDGXwOa6hmMEo8je9F7GG4ogyqSyrYg3+3INkrxPsoDkFF+UXYasaecTgAjwAmGFL1VE9I7f7iNuZHyYi9vr86B39orDmG6CR6Cx43PNxRVNPCS2LHm8tQAGxd4Rbe97o0r52W1wm8AIzObxLRtxHJpKatGjAxEzeWLWrsfRP3oPcR38wnsbpcZ3icNB9d8BIFXdsUGTp/S4MElvHASGLnzXdEXmQd41CTpVb53O4h0klVO8ji89/GqACeJp60New37yPbzgMSGUVV8addsbMYd6dsAKhKTGatWr0XX1YBK8ydbeIToq2laDH8YlJ6SDGeQ63n1JyioPJvpS4kS/Vm63HiTXJ0HCaxeFtWBoawl/91nr6UDzderr5TJBI8tm3Y7e6eWR/Wcfx3Ff+64IIAMPbJcBhocvYce6qyBApMnVaz17QpwlKlLFp5yjM7TNh+lKAr7i5fdR0bDyr/Hn9Z1IpJTWOLu8vVPOhnxblsS5KXyA0+QQCMBHnfHfzjeqJFDn4T1Wu1nlx50LBKmiNsZ1ri0/KbeNRd648rJwh1HbRlgBM+MCF5E1y8vL3+GbqtVO/tvfkuMj5V3+Ox0EHPAw=
