AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda to handle switchboard API requests
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: cms-fronts
    App:
        Description: Application name
        Type: String
        Default: switchboard-api-lambda
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - CODE
            - PROD
        Default: CODE
    DeployBucket:
        Description: Bucket where RiffRaff uploads artifacts on deploy
        Type: String
        Default: facia-dist
    ApiId:
        Description: API GateWay ID
        Type: String
Conditions:
    ApiGatewayDeployed:
        # Convoluted way of saying the ApiId is not set
        Fn::Not:
            - Fn::Equals:
                - ""
                - Ref: ApiId
Resources:
    ExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Path: /
            Policies:
                - PolicyName: logs
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "logs:CreateLogGroup"
                            - "logs:CreateLogStream"
                            - "logs:PutLogEvents"
                        Resource: "arn:aws:logs:*:*:*"
                - PolicyName: lambda
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "lambda:InvokeFunction"
                        Resource: "*"
                - PolicyName: s3
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "s3:GetObject"
                            - "s3:PutObject*"
                        Resource:
                            - Fn::Join:
                                - ""
                                - - "arn:aws:s3:::facia-switches/"
                                  - Ref: Stage
                                  - "/*"
    SwitchesLambda:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket:
                    Ref: DeployBucket
                S3Key:
                    "Fn::Join":
                        - "/"
                        -
                            - Ref: Stage
                            - switchboardAPILambda
                            - switchesLambda
                            - artifact.zip
            Description: Handle switches requests
            Handler: switches.handler
            MemorySize: 128
            Role:
                "Fn::GetAtt": ["ExecutionRole", "Arn"]
            Runtime: nodejs4.3
            Timeout: 60
    SwitchesLambdaPermissions:
        Type: AWS::Lambda::Permission
        Condition: ApiGatewayDeployed
        Properties:
            Action: lambda:invokeFunction
            FunctionName:
                Fn::GetAtt:
                    - SwitchesLambda
                    - Arn
            Principal: apigateway.amazonaws.com
            SourceArn:
                Fn::Join:
                    - ""
                    -
                        - "arn:aws:execute-api:"
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - ":"
                        - Ref: ApiId
                        - "/*"
    StatusLambda:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket:
                    Ref: DeployBucket
                S3Key:
                    "Fn::Join":
                        - "/"
                        -
                            - Ref: Stage
                            - switchboardAPILambda
                            - statusLambda
                            - artifact.zip
            Description: Handle status requests
            Handler: status.handler
            MemorySize: 128
            Role:
                "Fn::GetAtt": ["ExecutionRole", "Arn"]
            Runtime: nodejs4.3
            Timeout: 60
    StatusLambdaPermissions:
        Type: AWS::Lambda::Permission
        Condition: ApiGatewayDeployed
        Properties:
            Action: lambda:invokeFunction
            FunctionName:
                Fn::GetAtt:
                    - StatusLambda
                    - Arn
            Principal: apigateway.amazonaws.com
            SourceArn:
                Fn::Join:
                    - ""
                    -
                        - "arn:aws:execute-api:"
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - ":"
                        - Ref: ApiId
                        - "/*"
    ToggleLambda:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket:
                    Ref: DeployBucket
                S3Key:
                    "Fn::Join":
                        - "/"
                        -
                            - Ref: Stage
                            - switchboardAPILambda
                            - toggleLambda
                            - artifact.zip
            Description: Handle status requests
            Handler: toggle.handler
            MemorySize: 128
            Role:
                "Fn::GetAtt": ["ExecutionRole", "Arn"]
            Runtime: nodejs4.3
            Timeout: 60
    ToggleLambdaPermissions:
        Type: AWS::Lambda::Permission
        Condition: ApiGatewayDeployed
        Properties:
            Action: lambda:invokeFunction
            FunctionName:
                Fn::GetAtt:
                    - ToggleLambda
                    - Arn
            Principal: apigateway.amazonaws.com
            SourceArn:
                Fn::Join:
                    - ""
                    -
                        - "arn:aws:execute-api:"
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - ":"
                        - Ref: ApiId
                        - "/*"
